// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrdLogicLib.Storage;

#nullable disable

namespace OrdLogicLib.Storage.Migrations
{
    [DbContext(typeof(OrdersLogicDataContext))]
    [Migration("20230326150858_OrdersLogicDB")]
    partial class OrdersLogicDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrdLogicLib.Models.OrderModel", b =>
                {
                    b.Property<Guid>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdOrder");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrdLogicLib.Models.PaymentModel", b =>
                {
                    b.Property<Guid>("IdOrder")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTranche")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdOrder", "IdTranche");

                    b.HasIndex("IdTranche");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("OrdLogicLib.Models.TrancheModel", b =>
                {
                    b.Property<Guid>("IdTranche")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Residual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TrancheDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdTranche");

                    b.ToTable("Tranches");
                });

            modelBuilder.Entity("OrdLogicLib.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserOrdersIdGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex("UserOrdersIdGuid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OrdLogicLib.Models.PaymentModel", b =>
                {
                    b.HasOne("OrdLogicLib.Models.OrderModel", "OrderModel")
                        .WithMany()
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrdLogicLib.Models.TrancheModel", "TrancheModel")
                        .WithMany()
                        .HasForeignKey("IdTranche")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderModel");

                    b.Navigation("TrancheModel");
                });

            modelBuilder.Entity("OrdLogicLib.Models.UserModel", b =>
                {
                    b.HasOne("OrdLogicLib.Models.OrderModel", "OrderModel")
                        .WithOne()
                        .HasForeignKey("OrdLogicLib.Models.UserModel", "UserOrdersIdGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderModel");
                });
#pragma warning restore 612, 618
        }
    }
}
